---
title: "data_wrangling"
author: "Daphne Hoh"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r env prep}
setwd("C:/Users/taibi/Documents/GitHub/BiodiversityDataGapTW/shinyapp-zh/")

.packs <- c("httr", "jsonlite", "data.table",
            "dplyr", "stringr", "tidyverse",
            "sf", "parallel", "lwgeom")

sapply(.packs, require, character.only = TRUE)
```

```{r load TBIA data}
tbia <- fread("C:/Users/taibi/Documents/GitHub/TBIA-data-review/02.processed_data/ver5_ver20240704_shiny/tbia5_vtaxa.csv",
              sep = ",", colClasses = "character", encoding = "UTF-8", na.strings = c("", "NA", "N/A"))

names(tbia)
head(tbia)

# remove unwanted columns
keep <- c("id", "year", "month",
          "latitude", "longitude", "coordinatePrecision", "coordinateUncertaintyInMeters",
          "taxonID", "taxonRank", "taxaSubGroup",
          "kingdom", "phylum", "class", "order", "family", "genus", "scientificName", "simple_scientificName")

tbia <- tbia %>%
  select(all_of(keep))
```



```{r load TaiCOL data}
# download full TaiCOL list at https://taicol.tw/static/upload/TaiCOL_taxon_20240621.zip

keep <- c("rank","taxon_id","simple_name","common_name_c",
          "is_endemic","alien_type","is_terrestrial","is_freshwater","is_brackish","is_marine","is_in_taiwan",
          "kingdom","kingdom_c","phylum","phylum_c","class","class_c","order","order_c","family","family_c","genus","genus_c")
          
df.taicol.list <- fread("www/data/raw/TaiCOL_taxon_20240621.csv", select = keep,
                        sep = ",", colClasses = "character", encoding = "UTF-8", na.strings = c("", "NA", "N/A"))

df.taicol.list <- df.taicol.list %>% 
  filter(is_in_taiwan == "true") # 94,684

# add a simple_scientificName column to extract species name without infraspecies for some stats
df.taicol.list$simple_scientificName <- str_extract(df.taicol.list$simple_name, "^\\w+ \\w+") 

# use same column name
names(df.taicol.list)
names(df.taicol.list)[1] <- "taxonRank"
names(df.taicol.list)[2] <- "taxonID"

# change string from title to lower case
df.taicol.list$taxonRank <- tolower(df.taicol.list$taxonRank)
```

```{r prep: make taxaSubGroup in TaiCOL list}
# add a new column categorizing them into my defined taxaSubGroup
# make taxaSubGroup in df.taicol.list
`%ni%` <- Negate(`%in%`)

taxa <- df.taicol.list

taxa$micro <- fifelse(taxa$simple_name %in% c("Bacteria", "Archaea", "Protozoa", "Chromista"), paste0(taxa$simple_name), "x")
taxa$micro.k <- fifelse(taxa$kingdom %in% c("Bacteria", "Archaea", "Protozoa", "Chromista"), paste0(taxa$kingdom), "x")

taxa$virus <- fifelse(taxa$kingdom %in% c("Orthornavirae", "Bamfordvirae", "Heunggongvirae", "Pararnavirae", 
                                          "Ribozyviria kingdom incertae sedis", "Shotokuvirae", "Viruses kingdom incertae sedis"), "Viruses", "x")

taxa <- taxa %>%
  mutate(fungi = case_when(simple_name == "Fungi" ~ "Other fungi",
                           kingdom == "Fungi" & phylum %ni% c("Ascomycota", "Basidiomycota") ~ "Other fungi",
                           phylum == "Ascomycota" ~ "Ascomycota",
                           phylum == "Basidiomycota" ~ "Basidiomycota",
                           TRUE ~ "x"))

taxa <- taxa %>%
  mutate(plant.tmp = case_when(simple_name == "Plantae" ~ "Other plants",
                               kingdom == "Plantae" & is.na(phylum) ~ "Other plants",
                               kingdom == "Plantae" & phylum %in% c("Charophyta", "Chlorophyta", "Rhodophyta") ~ "Algae",
                               kingdom == "Plantae" & phylum %in% c("Anthocerotophyta", "Bryophyta", "Marchantiophyta") ~ "Mossess",
                               kingdom == "Plantae" & class %in% c("Polypodiopsida", "Lycopodiopsida") ~ "Ferns",
                               kingdom == "Plantae" & class == "Magnoliopsida" ~ "Angiosperms",
                               kingdom == "Plantae" & class %in% c("Cycadopsida", "Ginkgoopsida", "Pinopsida") ~ "Gymnosperms",
                               TRUE ~ "x"))
taxa$plant <- fifelse(taxa$kingdom == "Plantae" & taxa$plant.tmp == "x", "Other plants", paste0(taxa$plant.tmp))          

taxa <- taxa %>%
  mutate(animal.tmp = case_when(simple_name == "Animalia" ~ "Other animals",
                                kingdom == "Animalia" & phylum == "Chordata" & class %in% 
                                  c("Chondrichthyes", "Actinopterygii", "Actinopteri", "Elasmobranchii", "Holocephali", "Myxini") ~ "Fishes",
                                kingdom == "Animalia" & phylum == "Chordata" & class == "Aves" ~ "Birds",
                                kingdom == "Animalia" & phylum == "Chordata" & class == "Amphibia" ~ "Amphibians",
                                kingdom == "Animalia" & phylum == "Chordata" & class == "Reptilia" ~ "Reptiles",
                                kingdom == "Animalia" & phylum == "Chordata" & class == "Mammalia" ~ "Mammals",
                                kingdom == "Animalia" & phylum == "Chordata" & class == "NA" ~ "Other chordates",
                                kingdom == "Animalia" & class == "Insecta" & order == "Coleoptera" ~ "Coleoptera",
                                kingdom == "Animalia" & class == "Insecta" & order == "Lepidoptera" ~ "Lepidoptera",
                                kingdom == "Animalia" & class == "Insecta" & order %ni% c("Coleoptera", "Lepidoptera") ~ "Other insects",
                                kingdom == "Animalia" & phylum == "Arthropoda" & class == "Insecta" & is.na(order) ~ "Other insects",
                                kingdom == "Animalia" & phylum == "Arthropoda" & class == "Arachnida" ~ "Arachnida",
                                kingdom == "Animalia" & phylum == "Arthropoda" & class == "Malacostraca" ~ "Malacostraca",
                                kingdom == "Animalia" & phylum == "Arthropoda" & class %ni% c("Insecta" ,"Arachnida", "Malacostraca") ~ "Other arthropods",
                                kingdom == "Animalia" & phylum == "Arthropoda" & is.na(class) ~ "Other arthropods",
                                kingdom == "Animalia" & phylum == "Mollusca" & class == "Bivalvia" ~ "Bivalves",
                                kingdom == "Animalia" & phylum == "Mollusca" & class == "Gastropoda" ~ "Gastropods",
                                kingdom == "Animalia" & phylum == "Mollusca" & class == "Cephalopoda" ~ "Cephalopods",
                                kingdom == "Animalia" & phylum == "Mollusca" & class %ni% c("Bivalvia", "Gastropoda", "Cephalopoda") ~ "Other molluscs",
                                kingdom == "Animalia" & phylum == "Mollusca" & is.na(class) ~ "Other molluscs",
                                kingdom == "Animalia" & phylum == "Cnidaria" ~ "Cnidarians",
                                kingdom == "Animalia" & phylum == "Echinodermata" ~ "Echinoderms",
                                kingdom == "Animalia" & is.na(phylum) ~ "Other animals",
                                TRUE ~ "x"))
taxa$animal <- fifelse(taxa$kingdom == "Animalia" & taxa$animal.tmp == "x", "Other animals", paste0(taxa$animal.tmp))                                     

# combine and make taxaSubGroup
taxa1 <- taxa %>%
  mutate_all(~ifelse(. == 'x', NA, .)) %>%
  unite(taxaSubGroup, micro, micro.k, virus, fungi, plant, animal, sep = ",", remove = T, na.rm = T) %>%
  select(-c(plant.tmp, animal.tmp, is_in_taiwan))

# those with incomplete taxa levels so the categorizing failed
table(taxa1$taxaSubGroup) # 32 empty
taxa1 <- taxa1 %>% 
  mutate(taxaSubGroup = replace(taxaSubGroup, taxaSubGroup %in% "", "Unclassified"))

```

```{r prep: TaiCOL habitats}
## keep habitats to 'yes' only for easier filtering (i.e. make 'false' as NA)
taxa2 <- taxa1 %>% 
  mutate(is_terrestrial = replace(is_terrestrial, is_terrestrial == "true", "is_terrestrial")) %>% 
  mutate(is_freshwater = replace(is_freshwater, is_freshwater == "true", "is_freshwater")) %>% 
  mutate(is_brackish = replace(is_brackish, is_brackish == "true", "is_brackish")) %>% 
  mutate(is_marine = replace(is_marine, is_marine == "true", "is_marine"))

# final TaiCOL table that classified with taxaSubGroup
fwrite(taxa2, "www/data/processed/TaiCOL_taxon_20240621_taxaSubGroup.csv",
       row.names = F, quote = T)
```

```{r prep: add habitat info to TBIA table}
taxa2 <- fread("www/data/processed/TaiCOL_taxon_20240621_taxaSubGroup.csv", 
              sep = ",", colClasses = "character", encoding = "UTF-8", na.strings = c("", "NA", "N/A"))

habitat <- select(taxa2, taxonID, is_terrestrial, is_freshwater, is_brackish, is_marine)
tbia1 <- left_join(tbia, habitat, by = "taxonID")

fwrite(tbia1, "www/data/processed/tbia_habitat.csv",
       row.names = F, quote = T)
```


# Load updated TBIA & TaiCOL table
```{r updated TBIA & TaiCOL table}
tbia <- fread("www/data/processed/tbia_habitat.csv", 
              sep = ",", colClasses = "character", encoding = "UTF-8", na.strings = c("", "NA", "N/A"))

taicol <- fread("www/data/processed/TaiCOL_taxon_20240621_taxaSubGroup.csv", 
              sep = ",", colClasses = "character", encoding = "UTF-8", na.strings = c("", "NA", "N/A"))
```


```{r prep for Section: Taxonomic}
# Subsection: Taxonomic Gap

# (1)
## % record matched to highest taxon rank
df_taxa.rank <- data.frame(table(tbia$taxonRank))
names(df_taxa.rank) <- c("rank", "count")

## show Linnaean rank only
linnaean <- c("kingdom", "phylum", "class", "order", "family", "genus", "species")

### grouping the subs together
df_taxa.rank$taxonRank <- fifelse(!df_taxa.rank$rank %in% linnaean,
                                  "non-Linnaean", 
                                  paste0(df_taxa.rank$rank))

df_taxa.rank <- df_taxa.rank %>%
  group_by(taxonRank) %>%
  summarise(count = sum(count)) %>%
  mutate(proportion = count / sum(count) * 100) %>%
  arrange(desc(proportion))

fwrite(df_taxa.rank, "www/data/processed/df_taxa.rank.csv", 
       row.names = F, quote = T)  


# (2)
## % record (infra)species rank matched to TaiCOL
species_infraspecies <- c("species", "subspecies", "variety", "subvariety", "form", "subform", "special form")

df_taxa.rank.at.species <- tbia %>%
  filter(taxonRank %in% species_infraspecies) %>%
  summarise(count = n_distinct(simple_scientificName)) %>%
  mutate(proportion = count / 64508 * 100) %>% # TaiCOL last stats 20240704
  bind_rows(data.frame(count = 64508 - .$count, proportion = 100 - .$proportion)) %>% # 拿 TaiCOL 總數來減掉已記錄的數量
  mutate(category = c("入口網有記錄", "入口網未記錄"))

fwrite(df_taxa.rank.at.species, "www/data/processed/df_taxa.rank.at.species.csv", 
       row.names = F, quote = T)


# (3)
## The XX% of the unrecorded TaiCOL taxa on TBIA
### Select habitat: All
species_infraspecies <- c("species", "subspecies", "variety", "subvariety", "form", "subform", "special form")

taicol.group.all <- taicol %>%
  filter(taxonRank %in% species_infraspecies) %>%
  distinct(taxaSubGroup, simple_scientificName, .keep_all = TRUE) %>% 
  group_by(taxaSubGroup) %>%
  summarise(taicol.count = n())

sum(taicol.group.all$taicol.count) # 63,789 species level (excluding infraspecies)

### get total number of species (un)recorded in TBIA
df_taxa.unrecorded.taxa.prop <- tbia %>%
  filter(taxonRank %in% species_infraspecies) %>%
  distinct(taxaSubGroup, simple_scientificName, .keep_all = TRUE) %>%
  group_by(taxaSubGroup) %>%
  summarise(record.count = n())

### combine counts of TBIA + TaiCOL above
df_taxa.unrecorded.taxa.prop.groupAll <- left_join(taicol.group.all, df_taxa.unrecorded.taxa.prop, by = "taxaSubGroup")

df_taxa.unrecorded.taxa.prop.groupAll <-  df_taxa.unrecorded.taxa.prop.groupAll %>%
  rowwise() %>%
  mutate(record.prop = round(record.count / taicol.count * 100, 2),
         taicol.prop = round(100 - record.prop, 2)) %>%
  ungroup() %>%
  filter(taxaSubGroup != "Unclassified") %>%
  mutate_all(~replace_na(., 0)) %>%
  mutate(cum.total = taicol.count - record.count)

fwrite(df_taxa.unrecorded.taxa.prop.groupAll, "www/data/processed/df_taxa.unrecorded.taxa.prop.groupAll.csv", 
       row.names = F, quote = T)


### Select habitat: separate them by habitats
#### function for processing habitats and counts
process_habitats <- function(df) {
  
  habitats <- c("is_terrestrial", "is_freshwater", "is_brackish", "is_marine")

  # summarise count by habitat
  df_taxa.unrecorded.taxa.prop.habitats <- map(habitats, ~{
    df %>%
      filter(taxonRank == "species") %>%
      distinct(taxaSubGroup, simple_scientificName, .keep_all = TRUE) %>%
      group_by(taxaSubGroup, .data[[.x]]) %>% # group and count separately for each habitat
      summarise(record.count = n())
  })
  
  # rename column name of each habitat "is_*" to "habitat" for easy grouping
  for (i in seq_along(df_taxa.unrecorded.taxa.prop.habitats)) { 
    df_taxa.unrecorded.taxa.prop.habitats[[i]] <- rename(df_taxa.unrecorded.taxa.prop.habitats[[i]], habitat = 2)
  }
  
  group.habitats.df <- do.call(rbind, df_taxa.unrecorded.taxa.prop.habitats) %>%
    filter(!is.na(habitat) & habitat != "false") # excluding NA and false count
  
  return(group.habitats.df)
}

#### apply summarize function
taicol_habitat_count <- process_habitats(taicol)
tbia_habitat_count <- process_habitats(tbia)

#### combine the counts
names(taicol_habitat_count)[3] <- "taicol.count"

df_counts_by_habitats <- left_join(taicol_habitat_count, tbia_habitat_count, by = c("taxaSubGroup", "habitat")) %>%
  filter(taxaSubGroup != "Unclassified") %>%
  mutate_all(~replace_na(., 0)) %>%
  mutate(cum.total = taicol.count - record.count)
  

fwrite(df_counts_by_habitats, "www/data/processed/df_counts_by_habitats.csv", 
       row.names = F, quote = T)



# Subsection: Species Tree
taicol_species <- taicol %>%
  filter(taxonRank %in% species_infraspecies) %>%
  distinct(taxaSubGroup, simple_scientificName, .keep_all = TRUE) %>%
  select(taxonID, taxaSubGroup, family, genus, simple_scientificName) %>%
  filter(if_all(everything(), ~ !grepl("incertae sedis", ., ignore.case = TRUE))) # remove rows containing 'incertae sedis'

tbia_recorded_species <- tbia %>%
  filter(taxonRank %in% species_infraspecies) %>%
  distinct(taxaSubGroup, simple_scientificName, .keep_all = TRUE) %>%
  select(taxonID)
  
taicol_species$tbia.recorded <- ifelse(taicol_species$taxonID %in% tbia_recorded_species$taxonID, TRUE, FALSE)

table(taicol_species$tbia.recorded)

taicol_species$recorded <- fifelse(taicol_species$tbia.recorded == TRUE, 
                                   paste0("[Recorded] ", taicol_species$simple_scientificName), taicol_species$simple_scientificName)

fwrite(taicol_species, "www/data/processed/df_tree.csv", 
       row.names = F, quote = T)

### Unrecorded taxa for download
taicol_species_unrecorded <- taicol_species %>%
  filter(tbia.recorded == FALSE) %>%
  select(-tbia.recorded, -simple_scientificName) %>%
  filter(!is.na(recorded))

colnames(taicol_species_unrecorded)[5] <- "unrecorded"

fwrite(taicol_species_unrecorded, "www/data/processed/df_tree_unrecorded_list.csv", 
       row.names = F, quote = T)
```


```{r prep for Section: Temporal}
df_time <- tbia[, c("id", "year", "month", "taxaSubGroup")]

df_time <- df_time %>%
  group_by(taxaSubGroup, year, month) %>%
  summarise(occCount = n()) %>%
  mutate(month = sub("^0", "", month))

fwrite(df_time, "www/data/processed/df_time.csv", 
       row.names = F, quote = T)
```


```{r prep for Section: Spatial}
# load the 5km grid file
grid5km_sf <- st_read("www/data/layers/TWshp_land&sea_grids/TWshp_grid5km_landType.shp") %>%
  select(id, center_x, center_y, geometry, landType)

# load the tbia table
df_map <- tbia[, c("id", "longitude", "latitude", "coordinatePrecision", "coordinateUncertaintyInMeters", "taxaSubGroup")] %>%
  mutate(longitude = as.numeric(longitude), latitude = as.numeric(latitude), 
         coordinatePrecision = as.numeric(coordinatePrecision),
         coordinateUncertaintyInMeters = as.numeric(coordinateUncertaintyInMeters))

## 1. exclude uncertainty in distance
table(df_map$coordinatePrecision)
table(df_map$coordinateUncertaintyInMeters)
df_map <- df_map[df_map$coordinateUncertaintyInMeters < 5000 | is.na(df_map$coordinateUncertaintyInMeters)] # exclude < 5km (5000 meter) for 5km grid plotting, 1,180,542 excluded

## 2. map All records to grid
df_map_stats <- df_map %>% 
  group_by(taxaSubGroup, latitude, longitude) %>% 
  count()

# separate to group for parallel processing
n <- 200000
num_groups <- ceiling(nrow(df_map_stats) / n)
records_in_last_group <- nrow(df_map_stats) %% n
group_var <- rep(1:num_groups, each = n)
group_var <- c(group_var, rep(num_groups + 1, times = records_in_last_group))
df_map_stats_groupList <- split(df_map_stats, group_var)

catchLocation <- function(x){
  x %>%
    st_as_sf(coords = c("longitude", "latitude"), remove = FALSE) %>% # set coordinates
    st_set_crs(4326) %>%  # table transform to polygon
    st_join(., dg_grid, join = st_intersects, left = TRUE, largest = TRUE) %>% 
    st_drop_geometry(.)
}

#### parallel ####
cpu.cores <- detectCores() - 8
cl <- makeCluster(cpu.cores)
clusterEvalQ(cl, { # make sure all clusters are ready
  library(tidyverse)
  library(data.table)
  library(sf)
  library(lwgeom)
  dg_grid <- st_read("www/data/layers/TWshp_land&sea_grids/TWshp_grid5km_landType.shp")
  dg_grid <- as(dg_grid, "sf")%>%
    st_set_crs(4326)
  sf_use_s2(F)
}
)

system.time(
  df_map_grid <- parLapply(cl, df_map_stats_groupList, catchLocation)%>% 
    do.call(rbind,.)
  ) 

stopCluster(cl)


### 3 make all records table
allOccCount_grid_table <- df_map_grid %>% 
  group_by(taxaSubGroup) %>% 
  summarise(allOccCount = sum(n))

fwrite(allOccCount_grid_table, "www/data/processed/df_spatial_allOccCount_grid_table.csv", 
       row.names = F, quote = T)


### 4 make All records shp
allOccCount <- df_map_grid %>% 
  group_by(id) %>% 
  summarise(occCount = sum(n))


### 4.1 combine grid counts with 5km geometry
allOccCount_grid <- merge(allOccCount, grid5km_sf, by = "id", all.x = TRUE)
st_write(allOccCount_grid, "www/data/processed/df_map.shp", append = FALSE)


### 5 make taxaSubGroup map
taxaOccCount <- df_map_grid %>% 
  group_by(taxaSubGroup, id) %>% 
  summarise(occCount = sum(n))

### 5.1 combine grid counts with 5km geometry
taxaOccCount_grid <- merge(taxaOccCount, grid5km_sf, by = "id", all.x = TRUE)
names(taxaOccCount_grid) <- c("id", "tSG", "occCount", "center_x", "center_y", "landType", "geometry") # rename because ESRI cannot save long field name
st_write(taxaOccCount_grid, "www/data/processed/df_taxa_map.shp", append = FALSE)
```



```{r prep for Section: Gap}
# determine gap level & save as shp file
df_gapCount <- st_read("www/data/processed/df_map.shp")
summary(df_gapCount$occCount)

## df_gapCount contains only grid with at least 1 occCount, merge with grid5km_sf to get all grid (include those with 0 occCount)
df_gapCount_with0 <- left_join(as.data.frame(grid5km_sf), as.data.frame(df_gapCount), by = "id") %>% 
  select(c(id, occCount, center_x.x, center_y.x, landType.x, geometry.x)) %>%
  rename_with(~str_remove(., "\\.x$"), ends_with(".x")) %>%
  mutate(occCount = replace_na(occCount, 0))
  
# calculate gap level mean
grid5km_sf <- st_read("www/data/layers/TWshp_land&sea_grids/TWshp_grid5km_landType.shp")
number_of_grids_5km <- nrow(grid5km_sf)

sum(df_gapCount_with0$occCount) / number_of_grids_5km # 3392.8
## use 3,000 as average for gap level
## i.e. each grid has to contain at least 3,000 records to be considered as non-priority

df_gapCount_with0 <- df_gapCount_with0 %>%
  mutate(priority = case_when(occCount < 1000 ~ "建議優先填補",
                              occCount >= 1000 & occCount < 3000 ~ "建議填補",
                              occCount >= 3000 ~ "資料筆數高於平均值"))

st_write(df_gapCount_with0, "www/data/processed/df_gapCount_table.shp",
         row.names = F, quote = T, append = FALSE, layer_options = "ENCODING=UTF-8")



# save as table
df_gapCount_table <- as.data.frame(df_gapCount_with0) %>%
  group_by(priority, landType) %>%
  summarise(gridCount = n())
  
fwrite(df_gapCount_table, "www/data/processed/df_gapCount_table.csv", 
       row.names = F, quote = T)



# make CSV gap table for download
write.csv(df_gapCount_with0, "www/data/processed/df_gapCount_with0.csv", 
          row.names = F, quote = T)

# Preparation for Google My Map
df <- df_gapCount_with0

## create a list of data frames, split by priority and landType
split_dfs <- split(df, list(df$priority, df$landType))

## check their dim() as Google My Map only supports 2000 rows
for (name in names(split_dfs)) {
  cat("Dimensions of", name, ":", dim(split_dfs[[name]]), "\n")
}

split_large_df <- function(df, max_rows = 2000) {
  if (nrow(df) <= max_rows) {
    return(list(df))
  } else {
    part1 <- df %>% slice(1:max_rows)
    part2 <- df %>% slice((max_rows + 1):n())
    return(list(part1 = part1, part2 = part2))
  }
}

# Apply the function to each dataframe in split_dfs
split_dfs_adjusted <- lapply(names(split_dfs), function(name) {
  df <- split_dfs[[name]]
  split_result <- split_large_df(df)
  
  if (length(split_result) == 1) {
    return(setNames(split_result, name))
  } else {
    return(setNames(split_result, paste0(name, c("_part1", "_part2"))))
  }
})

# Flatten the list
split_dfs_final <- unlist(split_dfs_adjusted, recursive = FALSE)

for (name in names(split_dfs_final)) {
  cat("Dimensions of", name, ":", dim(split_dfs_final[[name]]), "\n")
}


###
for (name in names(split_dfs_final)) {
  # Check if the data frame is already an sf object
  if (!inherits(split_dfs_final[[name]], "sf")) {
    # If it's not an sf object but has a geometry column, convert it
    if ("geometry" %in% colnames(split_dfs_final[[name]])) {
      split_dfs_final[[name]] <- st_as_sf(split_dfs_final[[name]])
    } else {
      # If there's no geometry column, skip this data frame or handle the error
      warning(paste("Skipping", name, "- no geometry column found"))
      next
    }
  }
  
  # Write to KML
  st_write(split_dfs_final[[name]], 
           dsn = paste0("www/data/processed/GoogleMyMap/gmm_", name, ".kml"),
           driver = "KML",
           delete_dsn = TRUE)
}

```

